### ISSUE TITLE
Unable to add App Engine Module - Task 'appengineDownloadSdk' not found in root project 

### ISSUE THREAD

**Issue by PrashamTrivedi** [GoogleCloudPlatform/gradle-appengine-templates#54]
In latest android studio buid (141.2168647)

**Comment by loosebazooka** [comment]
That should work as is. 

Can you try to do a "Sync Project with Gradle Files" and see if the project appears fully formed?

**Comment by PrashamTrivedi** [comment]
There are two gradle tasks running at the time. This is the issue I receive once I finish the wizard. I have also tried "Sync Project With Gradle Files", which also did not work.

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Task 'appengineDownloadSdk' not found in root project 'AppEngineTest'.
>
>* Try:
>Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. >Run with --info or --debug option to get more log output.


From IDE logs it seems there are some template files which are missing, there are two stacktraces Caused by: java.io.FileNotFoundException for AndroidManifest.xml.ftl and build.gradle.ftl. 

Is there any template files or directory which is either missing or may be overriden?

I have some templates made in Studio 1.3. And For 1.4 I have accidently did a fresh installation, and then copied some directories (templates and pluggins) from 1.3 to 1.4 manually. I suspect this can be a case, but I also doubt some templates are missing,

**Comment by loosebazooka** [comment]
Yeah, I don't know if that's the best idea.

Our plugin's template lives in 

    android-studio/plugins/google-cloud-tools/lib/templates
    android-studio/plugins/google-cloud-tools/lib/clientTemplates

the files you're looking for should have been in clientTemplates

**Comment by PrashamTrivedi** [comment]
The files are indeed in the location you mentioned. 

Looks like this issue related to [Issue 183068](https://code.google.com/p/android/issues/detail?id=183068). Because when I dig up the log further I can see these lines

>2015-08-20 09:35:27,440 [ 308097]   INFO - gine.wizard.CloudTemplateUtils - Populating built-in App Engine templates... 
2015-08-20 09:35:34,283 [ 314940]  ERROR - plication.impl.ApplicationImpl - platform-tools doesn't match platform-tools-preview 
java.lang.AssertionError: platform-tools doesn't match platform-tools-preview
	at com.android.tools.idea.sdk.remote.UpdatablePkgInfo.checkInstallId(UpdatablePkgInfo.java:95)
	at com.android.tools.idea.sdk.remote.UpdatablePkgInfo.addRemote(UpdatablePkgInfo.java:68)
	at com.android.tools.idea.sdk.SdkPackages.computeUpdates(SdkPackages.java:131)
	at com.android.tools.idea.sdk.SdkPackages.setRemotePkgInfos(SdkPackages.java:115)
	at com.android.tools.idea.sdk.SdkState$LoadTask.run(SdkState.java:352)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)


I have to check with updated tools. May be this issue can be resolved after that.

**Comment by ngamolsky** [comment]
I too am having this issue!
